server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.56.104:3306/novel?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  logging:
    level:
      com:
        example:
          debug

  # application.yml
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

    # application.yml
  spring:
    mvc:
      static-path-pattern: /**
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - file:/path/to/your/static/files/

